id: P003080
initial_creation_type: ocr
source_metadata:
  id: bdr:W19803
  title: མི་སྣ
  author: ''
  volumes:
    5648adf9799448da9164e6baf077ae12:
      image_group_id: I4201
      title: ''
      volume_number: 1
      total_pages: 1044
      base_file: v001.txt
